### ISSUE TITLE
xpath `following-sibling` doesn't work when chaining locators

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/playwright-ui5#41]
```ts
await page.locator("ui5_css=sap.m.Text").locator("ui5_xpath=./following-sibling::*").count() // 0
```
this is because the DOM passed to the selector engine only contains the xml relative to its parent element, with the parent element as the root node (there can only be 1 root node)

i assumed this is how the built in `xpath` selector engine works too, but i guess not. need to figure out how that one works and try to replicate that

**Comment by KotlinIsland** [comment]
`xpath=div` == `xpath=./div`
`xpath=/div` means from the root node, any child
`xpath=//div` means from the root node, any descendant
```ts
page.setContent(`
<div>
    <span>child</span>
</div>
<span>sibling</span>
`)
page.locator("xpath=html/body/div").locator("xpath=following-sibling::span").innerText()  // sibling
```
