### ISSUE TITLE
Remove the redundant `sap.` at the start of the selectors

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/playwright-ui5#6]
Could we also hoist the most common package to the top level? ie `sap.m.Button` => `Button`. (I'm not actually sure what this package would be though, maybe it's `m`, maybe it's `ui`, who knows!)

**Comment by DetachHead** [comment]
> Could we also hoist the most common package to the top level? ie `sap.m.Button` => `Button`. (I'm not actually sure what this package would be though, maybe it's `m`, maybe it's `ui`, who knows!)

i decided against this as it seems sus, both `m` and `ui` are quite common so i think it's weird to default to one especially when all it would do is save typing two characters

**Comment by KotlinIsland** [comment]
True, and also `sap.m.ui` could collide if hoisted.
